#
# SPDX-FileCopyrightText: Copyright The Thingsboard Authors
# SPDX-License-Identifier: Apache-2.0
#

services:
  postgres:
    restart: "no"
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - tb-postgres-data:/var/lib/postgresql/data
  cassandra:
    restart: "no"
    image: "cassandra:5.0"
    ports:
      - "9042:9042"
    volumes:
      - tb-cassandra-data:/var/lib/cassandra
  tb-core1:
    env_file:
      - tb-node.hybrid.env
    depends_on:
      - postgres
      - cassandra
  tb-core2:
    env_file:
      - tb-node.hybrid.env
    depends_on:
      - postgres
      - cassandra
  tb-rule-engine1:
    env_file:
      - tb-node.hybrid.env
    depends_on:
      - postgres
      - cassandra
  tb-rule-engine2:
    env_file:
      - tb-node.hybrid.env
    depends_on:
      - postgres
      - cassandra

volumes:
  tb-postgres-data:
  tb-cassandra-data:
